# Generated by Django 5.0.2 on 2024-02-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100, verbose_name='task title')),
                ('description', models.CharField(default='None', max_length=255, null=True, verbose_name='task description')),
                ('priority', models.PositiveIntegerField(choices=[(1, 'Urgent'), (2, 'Normal'), (3, 'Lazy')], default=2, verbose_name='task title')),
            ],
        ),
    ]
