# Generated by Django 5.0.2 on 2024-02-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priority']},
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('priority__in', [1, 2, 3])), name='cluster_priority_valid'),
        ),
    ]
